version: 0.1
variables:
  BRANCH_NAME: “develop”
  MAJOR_VERSION: “1”
  MINOR_VERSION: “0”
  GIT_REPO: “https://github.com/shobha-venkatesh/golang-deployment-pipeline.git"
parameter-store:
  GIT_USER: "GIT_USERNAME"
  GIT_PASS: “GIT_PWD”
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:
      # - echo “machine git-codecommit.us-west-2.amazonaws.com” >> ~/.netrc
      - echo "$GIT_REPO"
      - echo “login $GIT_USER” >> ~/.netrc
      - echo “password $GIT_PASS” >> ~/.netrc
      - git clone -b develop https://github.com/shobha-venkatesh/golang-deployment-pipeline.git
      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - cd golang-deployment-pipeline.git
      - bash git_tagging.sh
      - go build -o app

artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*
